# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#:~:text=A%20workflow%20is%20a%20configurable,or%20at%20a%20defined%20schedule.
name: workflow-de-los-pull-request
on:
  pull_request:
    braches:
      - main
jobs:
  contruir_y_testear:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: validar el repo
        uses: actions/checkout@v3
      
      - name: validar e instalar python
        uses: actions/setup-python@v4
      
      - name: instalar las librerias
        run: pip3 install -r requirements.txt

      - name: correr los tests
        run: pytest 